### ISSUE TITLE
kubernetes/rasa-en-deployment.yaml on kubernetes

### ISSUE THREAD

**Issue by fahr23** [souvikg10/rasa-latest#3]
Hello again:)
when using "docker-compose up" command all docker containers up and running. (OK)
 Kubernetes case, action and nlg deployments are up and running. (OK)
But in kubernetes, rasa-en-deployment does not start. (NOK)

I couldn't figure out the problem on the rasa-en-deployment file.

**Comment by souvikg10** [comment]
What was the error?

**Comment by fahr23** [comment]
![image](https://user-images.githubusercontent.com/969748/56869804-225b3580-6a0e-11e9-8130-35d3df16a0fc.png)

**Comment by fahr23** [comment]
rasa_en does not start on kubernetes and has not logged any messages.

**Comment by fahr23** [comment]
![image](https://user-images.githubusercontent.com/969748/56869829-8ed63480-6a0e-11e9-9e11-0a45cc03f330.png)

**Comment by souvikg10** [comment]
Strange. i need to try it again on my minikube. but i can't do it tonight. 
in the meantime,
can you check if the data folder is available inside the docker container with the models in it?

**Comment by fahr23** [comment]
The machine that run kubernetes gives   following error.
 rasa-latest_rasa_en_1 exited with code 132 

this error is not related to kubernetes:) Rasa related error.  
Thank you for your support.

I will close this issue because of rasa related or tensorflow related problem according to these links. 
https://github.com/RasaHQ/rasa/issues/1211#issuecomment-403855695
https://github.com/tensorflow/tensorflow/issues/19584
